/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.31
 * Generated at: 2020-03-31 17:17:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\" dir=\"ltr\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<title></title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"Menu\">\r\n");
      out.write("\t\t<h1 class=\"logo\">\r\n");
      out.write("\t\t\t<i class=\"fas fa-tooth\"></i>MedOne Dentist\r\n");
      out.write("\t\t</h1>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a href=\"#\"><i class=\"fas fa-home\"></i>Home</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\"><i class=\"fas fa-clone\"></i>Services</a>\r\n");
      out.write("\t\t\t\t<div class=\"sub-menu\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"http://localhost:8081/WebApplication/Register.jsp\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fas fa-user-plus\"></i>Registration </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"sub-log\"><a href=\"#\"><i class=\"fas fa-sign-in-alt\"></i>Login </a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"subb-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thref=\"http://localhost:8081/WebApplication/LoginPatient.jsp\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"fas fa-user-injured\"></i>Patient</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thref=\"http://localhost:8081/WebApplication/LoginDentist.jsp\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"fas fa-user-md\"></i>Dentist</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li><a href=\"#\"><i class=\"fas fa-phone\"></i>Contact</a>\r\n");
      out.write("\t\t\t\t<div class=\"sub-menu\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fas fa-envelope\"></i>Email</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fas fa-phone\"></i>Phone</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fab fa-twitter\"></i>Twiter</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\"><i class=\"fas fa-user\"></i>About us</a>\r\n");
      out.write("\t\t\t\t<div class=\"sub-menu\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Mission</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Vesion</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Team</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--Login-->\r\n");
      out.write("\t<div class=\"loginbox\">\r\n");
      out.write("\t\t<img src=\"avatar.png\" alt=\"\" class=\"avatar\">\r\n");
      out.write("\t\t<h1 class=\"Here\">Login Here</h1>\r\n");
      out.write("\t\t<form class=\"\" action=\"Login\" method=\"post\">\r\n");
      out.write("\t\t<div class=\"choix\">\r\n");
      out.write("\t\t\t<label class=\"LB\">Patient:</label><input class=\"Radio\" type=\"radio\"  name=\"RADIO\" value=\"Patient\">\r\n");
      out.write("\t\t\t<label class=\"LB\">Dentist:</label><input class=\"Radio\" type=\"radio\"  name=\"RADIO\" value=\"Dentist\">\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t\t<p>Username</p>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"one\" name=\"username\" value=\"\"\r\n");
      out.write("\t\t\t\tplaceholder=\"Enter username\">\r\n");
      out.write("\t\t\t<p>Password</p>\r\n");
      out.write("\t\t\t<input type=\"password\" class=\"one\" name=\"password\" value=\"\"\r\n");
      out.write("\t\t\t\tplaceholder=\"Enter password\">\t\r\n");
      out.write("\t\t    <input type=\"Submit\" class=\"btn\" value=\"Login\"> \r\n");
      out.write("\t\t    <a href=\"#\">Lost yourpassword?</a><br>\r\n");
      out.write("\t\t    <a href=\"http://localhost:8081/WebApplication/Register.jsp\">Don't have a account?</a>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
